version: '3.7'

services:

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build: ./server
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0.4
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
